---
- name: Configure hashed password for root user
  hosts: "{{ hosts_var | default('linux_servers') }}"
  become: yes
  gather_facts: yes

  tasks:
    - name: Download and install the EPEL release RPM
      get_url:
        url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
        dest: /tmp/epel-release-latest.rpm
      when: ansible_distribution == 'RedHat'

    - name: Install the EPEL release RPM
      command: yum localinstall -y /tmp/epel-release-latest.rpm
      args:
        creates: /etc/yum.repos.d/epel.repo
      when: ansible_distribution == 'RedHat'

    - name: Install pwgen
      package:
        name: pwgen
        state: present
      become: yes

    - name: Generate random password with pwgen
      command: pwgen -1 -s 12
      register: pwgen_output

    - name: Generate random salt
      shell: openssl rand -base64 12 | tr -dc 'a-zA-Z0-9'
      register: salt_output

    - name: Hash the diceware password with random salt
      set_fact:
        hashed_password: "{{ pwgen_output.stdout | password_hash('sha512', salt_output.stdout) }}"
      when: pwgen_output.rc == 0

    - name: Set hashed password for root user
      user:
        name: root
        password: "{{ hashed_password }}"
        update_password: always
      become: yes
      when: pwgen_output.rc == 0

    - name: Show the generated diceware password
      debug:
        var: pwgen_output.stdout

    - name: Show the hashed password
      debug:
        var: hashed_password

    - name: Remove output text file on the Ansible host
      local_action:
        module: file
        path: '/etc/ansible/output/change_password_output.txt'
        state: absent

    - name: Create output directory
      local_action: file
      args:
        path: '/tmp/password/'
        state: directory
        mode: '0755'

    - name: Copy the output to the Ansible host
      local_action:
        module: lineinfile
        path: '/tmp/password/change_password_output.txt'
        line: 'Hostname: {{ inventory_hostname }} Plain password: {{ pwgen_output.stdout}} Hashed password: {{ hashed_password  }} '
        create: yes