---
- name: Search for PID in Linux servers
  hosts: "{{ hosts_var | default('linux_servers') }}"
  gather_facts: true
  become: true
  vars:
    pid: "wazuh-agent"

  tasks:
    - name: Search for PID using pgrep
      shell: "pgrep -f '{{ pid }}'"
      register: pid_result
      ignore_errors: true

    - name: Display PID result
      debug:
        var: pid_result.stdout_lines